- name: Yum update packages
  yum: name=* state=latest

- name: jq install
  shell: sudo curl -o /usr/local/bin/jq -L https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && sudo chmod +x /usr/local/bin/jq

- name: latest docker install
  shell: curl -fsSL get.docker.com | bash

- name: start docker deamon
  service: name=docker state=started
